name: Build Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: |
            khalibre/elasticseach-liferay
            ghcr.io/Khalibre/elasticseach-liferay
          tags: |
            type=sha,enable=${{ github.event_name == 'push' }}
            type=ref,event=tag,enable=${{ github.event_name == 'push' }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'push' }}
            type=ref,event=branch,enable=${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./8
          push: true
          load: false
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
